### ISSUE TITLE
Création maquette sur Figma (Desktop - tablette - Mobile)

### ISSUE THREAD

**Issue by bouchat-marieange** [bouchat-marieange/Fil-Rouge-LJE-Application-Mobile#13]

**Comment by bouchat-marieange** [comment]
Voir pour ligne directrice la maquette papier dans le dossier maquette du projet

**Comment by bouchat-marieange** [comment]
Adresse maquette Figma: https://www.figma.com/file/ekNtiFHHAMBFLyLZ1pp3wkII/Maquette-LJE

**Comment by Ezaaii** [comment]
Done.
